import type {
  NewJobOpening,
  NewJobPostingSite,
  NewScoringFormula,
  NewTalentPool,
} from '../app/db/schema'

/**
 * Test scoring formulas with different weight profiles
 */
export const testFormulas: NewScoringFormula[] = [
  {
    name: 'Work-Life Balance',
    weights: {
      impact: 0.5,
      compensation: 0.8,
      role: 0.6,
      tech: 0.4,
      location: 1.0,
      industry: 0.3,
      culture: 1.0,
      growth: 0.5,
      profileMatch: 0.6,
      companySize: 0.4,
      stress: 1.0,
      jobSecurity: 0.9,
      wowBoost: 0.3,
    },
  },
  {
    name: 'Career Growth',
    weights: {
      impact: 1.0,
      compensation: 0.7,
      role: 1.0,
      tech: 0.8,
      location: 0.3,
      industry: 0.6,
      culture: 0.5,
      growth: 1.0,
      profileMatch: 0.9,
      companySize: 0.5,
      stress: 0.2,
      jobSecurity: 0.4,
      wowBoost: 0.8,
    },
  },
]

/**
 * Test job openings covering all statuses, countries, tracks, and scenarios
 */
export const testJobs: NewJobOpening[] = [
  // Not Applied - Remote engineering role in Germany (WOW)
  {
    title: 'Staff Software Engineer',
    company: 'Stripe',
    description:
      'Join our payments infrastructure team to build the next generation of financial APIs. You will work on distributed systems processing millions of transactions per second.',
    jobLocation: 'Berlin, Germany',
    country: 'DE',
    postingUrl: 'https://stripe.com/jobs/staff-engineer',
    dateOpened: '2026-01-15',
    wow: true,
    track: 'engineering',
    status: 'not_applied',
    salaryMin: 140000,
    salaryMax: 180000,
    salaryCurrency: 'EUR',
    pensionScheme: 'Company pension with 5% employer contribution',
    healthInsurance: 'Premium private health insurance',
    stockOptions: '0.05% equity package',
    vacationDays: 30,
    workLocation: 'remote',
    wfhDaysPerWeek: 5,
    ratingImpact: 1,
    ratingCompensation: 1,
    ratingRole: 1,
    ratingTech: 1,
    ratingLocation: 1,
    ratingIndustry: 1,
    ratingCulture: 1,
    ratingGrowth: 1,
    ratingProfileMatch: 1,
    ratingCompanySize: 0,
    ratingStress: 0,
    ratingJobSecurity: 1,
  },

  // Applied - Hybrid management role in Netherlands
  {
    title: 'Engineering Manager - Platform',
    company: 'Booking.com',
    description:
      'Lead a team of 8-10 engineers building our core platform services. Drive technical strategy and mentor team members while collaborating with product and design.',
    jobLocation: 'Amsterdam, Netherlands',
    country: 'NL',
    postingUrl: 'https://careers.booking.com/em-platform',
    dateOpened: '2026-01-10',
    wow: false,
    track: 'management',
    status: 'applied',
    appliedAt: new Date('2026-01-18'),
    salaryMin: 110000,
    salaryMax: 140000,
    salaryCurrency: 'EUR',
    pensionScheme: 'Dutch pension fund with employer match',
    healthInsurance: 'Standard Dutch health coverage',
    vacationDays: 25,
    workLocation: 'hybrid',
    officeDistanceKm: 15,
    wfhDaysPerWeek: 3,
    ratingImpact: 0,
    ratingCompensation: 0,
    ratingRole: 1,
    ratingTech: 0,
    ratingLocation: 1,
    ratingIndustry: 0,
    ratingCulture: 0,
    ratingGrowth: 1,
    ratingProfileMatch: 1,
    ratingCompanySize: -1,
    ratingStress: -1,
    ratingJobSecurity: 1,
  },

  // Interviewing - Office engineering role in UK (WOW)
  {
    title: 'Principal Engineer - AI Infrastructure',
    company: 'DeepMind',
    description:
      'Design and build the infrastructure powering cutting-edge AI research. Work alongside world-class researchers on systems that push the boundaries of machine learning.',
    jobLocation: 'London, United Kingdom',
    country: 'GB',
    postingUrl: 'https://deepmind.com/careers/principal-ai-infra',
    dateOpened: '2026-01-05',
    wow: true,
    track: 'engineering',
    status: 'interviewing',
    appliedAt: new Date('2026-01-08'),
    interviewingAt: new Date('2026-01-15'),
    salaryMin: 180000,
    salaryMax: 250000,
    salaryCurrency: 'GBP',
    pensionScheme: '10% employer pension contribution',
    healthInsurance: 'Comprehensive Bupa coverage',
    stockOptions: 'Alphabet RSUs',
    vacationDays: 28,
    workLocation: 'office',
    officeDistanceKm: 25,
    wfhDaysPerWeek: 0,
    ratingImpact: 1,
    ratingCompensation: 1,
    ratingRole: 1,
    ratingTech: 1,
    ratingLocation: 0,
    ratingIndustry: 1,
    ratingCulture: 1,
    ratingGrowth: 1,
    ratingProfileMatch: 1,
    ratingCompanySize: 0,
    ratingStress: -1,
    ratingJobSecurity: 1,
  },

  // Offer - Remote management role in France
  {
    title: 'VP of Engineering',
    company: 'Datadog',
    description:
      'Lead multiple engineering teams across our observability platform. Drive technical excellence, hiring, and cross-functional collaboration at scale.',
    jobLocation: 'Paris, France (Remote)',
    country: 'FR',
    postingUrl: 'https://careers.datadoghq.com/vp-engineering',
    dateOpened: '2025-12-20',
    wow: true,
    track: 'management',
    status: 'offer',
    appliedAt: new Date('2025-12-22'),
    interviewingAt: new Date('2026-01-02'),
    offerAt: new Date('2026-01-19'),
    salaryMin: 200000,
    salaryMax: 260000,
    salaryCurrency: 'EUR',
    pensionScheme: 'French statutory pension + supplementary plan',
    healthInsurance: 'Mutuelle premium tier',
    stockOptions: '0.1% equity over 4 years',
    vacationDays: 35,
    workLocation: 'remote',
    wfhDaysPerWeek: 5,
    ratingImpact: 1,
    ratingCompensation: 1,
    ratingRole: 1,
    ratingTech: 0,
    ratingLocation: 1,
    ratingIndustry: 1,
    ratingCulture: 1,
    ratingGrowth: 1,
    ratingProfileMatch: 1,
    ratingCompanySize: 0,
    ratingStress: -1,
    ratingJobSecurity: 0,
  },

  // Rejected - Hybrid engineering role in Spain
  {
    title: 'Senior Backend Engineer',
    company: 'Glovo',
    description:
      'Build scalable backend services for our delivery platform. Work with Go, Kubernetes, and event-driven architectures serving millions of users.',
    jobLocation: 'Barcelona, Spain',
    country: 'ES',
    postingUrl: 'https://jobs.glovoapp.com/senior-backend',
    dateOpened: '2025-12-15',
    wow: false,
    track: 'engineering',
    status: 'rejected',
    appliedAt: new Date('2025-12-18'),
    interviewingAt: new Date('2026-01-05'),
    rejectedAt: new Date('2026-01-12'),
    salaryMin: 70000,
    salaryMax: 90000,
    salaryCurrency: 'EUR',
    vacationDays: 23,
    workLocation: 'hybrid',
    officeDistanceKm: 8,
    wfhDaysPerWeek: 2,
    ratingImpact: 0,
    ratingCompensation: 0,
    ratingRole: 0,
    ratingTech: 1,
    ratingLocation: 1,
    ratingIndustry: 0,
    ratingCulture: 0,
    ratingGrowth: 0,
    ratingProfileMatch: 0,
    ratingCompanySize: 0,
    ratingStress: -1,
    ratingJobSecurity: -1,
  },

  // Ghosted - Remote engineering role in Germany
  {
    title: 'Lead Software Engineer',
    company: 'N26',
    description:
      'Lead technical initiatives in our mobile banking platform. Drive architecture decisions and mentor engineers in a fast-paced fintech environment.',
    jobLocation: 'Berlin, Germany',
    country: 'DE',
    postingUrl: 'https://n26.com/careers/lead-engineer',
    dateOpened: '2025-11-20',
    wow: false,
    track: 'engineering',
    status: 'ghosted',
    appliedAt: new Date('2025-11-25'),
    ghostedAt: new Date('2026-01-10'),
    salaryMin: 95000,
    salaryMax: 120000,
    salaryCurrency: 'EUR',
    pensionScheme: 'Company pension scheme',
    vacationDays: 28,
    workLocation: 'remote',
    wfhDaysPerWeek: 5,
    ratingImpact: 0,
    ratingCompensation: 0,
    ratingRole: 1,
    ratingTech: 0,
    ratingLocation: 1,
    ratingIndustry: 1,
    ratingCulture: null,
    ratingGrowth: 0,
    ratingProfileMatch: 0,
    ratingCompanySize: 0,
    ratingStress: null,
    ratingJobSecurity: -1,
  },

  // Not Applied - Hybrid engineering role in Netherlands
  {
    title: 'Senior Platform Engineer',
    company: 'Adyen',
    description:
      'Build and maintain our global payments infrastructure. Work on low-latency systems handling billions in transaction volume across multiple data centers.',
    jobLocation: 'Amsterdam, Netherlands',
    country: 'NL',
    postingUrl: 'https://careers.adyen.com/platform-engineer',
    dateOpened: '2026-01-20',
    wow: false,
    track: 'engineering',
    status: 'not_applied',
    salaryMin: 100000,
    salaryMax: 130000,
    salaryCurrency: 'EUR',
    pensionScheme: 'Competitive pension with employer contribution',
    healthInsurance: 'Premium health package',
    stockOptions: 'Employee stock purchase plan',
    vacationDays: 27,
    workLocation: 'hybrid',
    officeDistanceKm: 12,
    wfhDaysPerWeek: 2,
    ratingImpact: 1,
    ratingCompensation: 1,
    ratingRole: 0,
    ratingTech: 1,
    ratingLocation: 1,
    ratingIndustry: 1,
    ratingCulture: 0,
    ratingGrowth: 0,
    ratingProfileMatch: 1,
    ratingCompanySize: 0,
    ratingStress: 0,
    ratingJobSecurity: 1,
  },

  // Applied - Office management role in UK
  {
    title: 'Director of Engineering',
    company: 'Monzo',
    description:
      'Lead engineering for our lending products. Build and scale teams, drive technical strategy, and collaborate with product to deliver innovative banking features.',
    jobLocation: 'London, United Kingdom',
    country: 'GB',
    postingUrl: 'https://monzo.com/careers/director-engineering',
    dateOpened: '2026-01-12',
    wow: true,
    track: 'management',
    status: 'applied',
    appliedAt: new Date('2026-01-16'),
    salaryMin: 150000,
    salaryMax: 190000,
    salaryCurrency: 'GBP',
    pensionScheme: '6% employer pension contribution',
    healthInsurance: 'Private medical and dental',
    stockOptions: 'Generous equity package',
    vacationDays: 25,
    workLocation: 'office',
    officeDistanceKm: 30,
    wfhDaysPerWeek: 1,
    ratingImpact: 1,
    ratingCompensation: 1,
    ratingRole: 1,
    ratingTech: 0,
    ratingLocation: -1,
    ratingIndustry: 1,
    ratingCulture: 1,
    ratingGrowth: 1,
    ratingProfileMatch: 1,
    ratingCompanySize: 0,
    ratingStress: -1,
    ratingJobSecurity: 0,
  },

  // Interviewing - Remote engineering role in France
  {
    title: 'Staff Engineer - Data Platform',
    company: 'Criteo',
    description:
      'Architect and build data processing systems handling petabytes of data. Lead technical direction for our real-time bidding infrastructure.',
    jobLocation: 'Paris, France (Remote)',
    country: 'FR',
    postingUrl: 'https://careers.criteo.com/staff-data-platform',
    dateOpened: '2026-01-08',
    wow: false,
    track: 'engineering',
    status: 'interviewing',
    appliedAt: new Date('2026-01-11'),
    interviewingAt: new Date('2026-01-18'),
    salaryMin: 120000,
    salaryMax: 150000,
    salaryCurrency: 'EUR',
    pensionScheme: 'French pension scheme',
    healthInsurance: 'Top-tier mutuelle',
    stockOptions: 'RSU grant',
    vacationDays: 30,
    workLocation: 'remote',
    wfhDaysPerWeek: 5,
    ratingImpact: 0,
    ratingCompensation: 0,
    ratingRole: 1,
    ratingTech: 1,
    ratingLocation: 1,
    ratingIndustry: -1,
    ratingCulture: 0,
    ratingGrowth: 0,
    ratingProfileMatch: 1,
    ratingCompanySize: 0,
    ratingStress: 0,
    ratingJobSecurity: 0,
  },

  // Not Applied - Hybrid management role in Spain (WOW)
  {
    title: 'Head of Engineering',
    company: 'Typeform',
    description:
      'Lead all engineering at Typeform. Shape technical vision, build world-class teams, and drive innovation in our form-building platform used by millions.',
    jobLocation: 'Barcelona, Spain',
    country: 'ES',
    postingUrl: 'https://typeform.com/careers/head-engineering',
    dateOpened: '2026-01-18',
    wow: true,
    track: 'management',
    status: 'not_applied',
    salaryMin: 130000,
    salaryMax: 170000,
    salaryCurrency: 'EUR',
    pensionScheme: 'Enhanced pension plan',
    healthInsurance: 'Premium private health coverage',
    stockOptions: '0.15% equity',
    vacationDays: 25,
    workLocation: 'hybrid',
    officeDistanceKm: 5,
    wfhDaysPerWeek: 3,
    ratingImpact: 1,
    ratingCompensation: 1,
    ratingRole: 1,
    ratingTech: 0,
    ratingLocation: 1,
    ratingIndustry: 0,
    ratingCulture: 1,
    ratingGrowth: 1,
    ratingProfileMatch: 1,
    ratingCompanySize: 1,
    ratingStress: 0,
    ratingJobSecurity: 0,
  },
]

/**
 * Test job posting sites with varied lastCheckedAt dates
 */
export const testSites: NewJobPostingSite[] = [
  {
    name: 'LinkedIn - React Berlin',
    url: 'https://www.linkedin.com/jobs/search/?keywords=react&location=Berlin',
    lastCheckedAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
  },
  {
    name: 'Indeed - Engineering Manager',
    url: 'https://de.indeed.com/jobs?q=engineering+manager',
    lastCheckedAt: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1 day ago
  },
  {
    name: 'Hacker News - Who is Hiring',
    url: 'https://news.ycombinator.com/item?id=whoishiring',
    lastCheckedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000), // 6 days ago
  },
  {
    name: 'WeWorkRemotely',
    url: 'https://weworkremotely.com/categories/remote-full-stack-programming-jobs',
    lastCheckedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000), // 2 weeks ago
  },
  {
    name: 'Berlin Startup Jobs',
    url: 'https://berlinstartupjobs.com/engineering/',
    lastCheckedAt: null,
  },
]

/**
 * Test talent pools with varied statuses
 */
export const testPools: NewTalentPool[] = [
  {
    companyName: 'Stripe',
    url: 'https://stripe.com/jobs/talent',
    status: 'submitted',
    notes: 'Applied through referral from a friend.',
  },
  {
    companyName: 'Datadog',
    url: 'https://careers.datadoghq.com/talent-pool',
    status: 'submitted',
    notes: null,
  },
  {
    companyName: 'Vercel',
    url: 'https://vercel.com/careers/talent',
    status: 'not_submitted',
    notes: 'Saw this on Twitter, looks interesting.',
  },
  {
    companyName: 'Cloudflare',
    url: 'https://www.cloudflare.com/careers/talent-pool',
    status: 'not_submitted',
    notes: null,
  },
]
